### ISSUE TITLE
plugin misidentifies ament_cmake packages containing Cargo.toml

### ISSUE THREAD

**Issue by ottojo** [colcon/colcon-ros-cargo#23]
There is at least one package here https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/blob/main/package.xml#L36 which is explicitly of type ament_cmake but contains a Cargo.toml. This results in the package being identified as `ament_cargo` when this plugin is installed.

I would have expected the explicit specification in package.xml to always take precedence, and that's what was intended in the linked package

**Comment by ottojo** [comment]
Maybe the priority of `PackageIdentificationExtensionPoint` should be lower than that of  `RosPackageIdentification`?(https://github.com/colcon/colcon-ros/blob/master/colcon_ros/package_identification/ros.py#L25-L27)?

```
    # the priority needs to be higher than the extensions identifying packages
    # using the build systems supported by ROS (CMake and Python)
```

The choice of 160 (just above the `RosPackageIdentification` priority) seems oddly specific though, so i presume there was some intention behind that...

**Comment by luca-della-vedova** [comment]
Very valid points, yes I believe 160 was chosen precisely because it would take priority over 150 package identifications.
This seems to be a fairly common pain point as https://github.com/colcon/colcon-ros-cargo/pull/10, https://github.com/colcon/colcon-ros-cargo/pull/11 and https://github.com/colcon/colcon-cargo/pull/32 show.
I do agree with your point though, if there is a package.xml that explicitly sets the `build_type` it feels natural that it would override the package identification.
I wonder if something like https://github.com/colcon/colcon-ros-cargo/pull/10 would work? If a `package.xml` is detected, parse it and if the `build_type` is not `ament_cargo` return early

**Comment by luca-della-vedova** [comment]
#10 has been merged, I tested locally with the zenoh plugin you mentioned and it is now able to compile, closing but feel free to reopen if the issue still exists for you
